Parse switches from CLI
Glutexo/onigumo pull request #186
Opened 2023-06-09 09:29 UTC by nappex

Parse switches for work directory. If we want to parse work dir we have parse newly component also.

2023-06-09 09:32 UTC, nappex commented
I am not sure about naming the switches, `output` for working directory is not something obvious at first sight. `Working` means where `inputs` are saved or `output` should going to or `both` at one place.

2023-06-09 09:33 UTC, nappex commented
Other task what should be done are tests.
I have to more explore the ways how to test private functions.

2023-07-29 16:11 UTC, nappex commented
We should consider library [Optimus](https://github.com/funbox/optimus) for parsing cli arguments as far as the onigumo is CLI app.

2023-09-30 17:57 UTC, nappex commented on lib/cli.ex
> +      |> safe_concat()
We save the result to variable with name `module`, but the switch to be parse is called `component`. Would not be fancier when switch would be called as `module` also?

2023-10-01 16:52 UTC, nappex commented on lib/cli.ex
> +      |> safe_concat()
The variable name `module` is really module -> `Onigumo.Donwloader` is module and it is the thing we get from pipes to `module` variable.

2023-10-02 08:12 UTC, Glutexo requested changes
We should split the pull request into two separate ones:

- [ ] Switch to _OptionParser_. -> #189 
- [ ] The new _output_ argument.

Also, _output_ may not be the best name for the argument. It is more a “working directory” rather than an output. The actual “output” is what the Materializer spits out.

2024-02-24 21:21 UTC, Glutexo reviewed
❤️

2024-02-24 21:21 UTC, nappex commented
- [ ] Test working dir exist and contains corresponding files
- [ ] Test unreachable path, there is a file with same name with working-dir

2024-05-10 17:37 UTC, Glutexo commented
> * [ ]  Test working dir exist and contains corresponding files
> * [ ]  Test unreachable path, there is a file with same name with working-dir

For those, issues #218 and #219 were created.

2024-05-10 17:38 UTC, closed without merging