Shorten “URL address“ to just “address”
Glutexo/onigumo pull request #93
Opened 2022-07-06 13:29 UTC by Glutexo

I find the “URL address” expression too wordy. I picked “address,” but “URL” would be OK too. In English, I’d instead choose the “URL” version.

2022-07-09 19:33 UTC, Glutexo commented
I gave the text for a review and got the advice that using “URL” instead of just “address” would sound better, even in Czech. After all, this is a technical text. Still, using the complete form in the first appearance may look good.

I pushed a new version, so you can assess how it looks. I kept the full “URL address” form only in the first appearance in each section and just “URL” in all subsequent ones.

2022-07-10 09:17 UTC, nappex requested changes

2022-07-10 09:17 UTC, nappex commented on README.md
> +2. kontroly existence seznamu nových URB,
```suggestion
2. kontroly existence seznamu nových URL,
```

2022-07-10 09:17 UTC, nappex commented
Ok, it sounds good I agree.

2022-07-10 15:29 UTC, Glutexo commented on README.md
> +2. kontroly existence seznamu nových URB,
Nice catch!

2022-07-10 15:29 UTC, merged